version: "3"

services:
  app:
    image: our-covid-voices/admin/app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-3000}:80"
    command: npm run dev
    restart: on-failure
